// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {guiapp} from '../models';

export function CreateProject(arg1:string):Promise<guiapp.WorkItem>;

export function CreateTask(arg1:number,arg2:string):Promise<guiapp.WorkItem>;

export function CreateTimeEntry(arg1:guiapp.CreateTimeEntryRequest):Promise<guiapp.TimeEntry>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteTimeEntry(arg1:number):Promise<void>;

export function DiscardRunningStopwatch():Promise<void>;

export function DiscardStopwatch(arg1:number):Promise<void>;

export function GetDashboard():Promise<guiapp.Dashboard>;

export function GetTimeDay(arg1:string):Promise<guiapp.TimeDay>;

export function Init(arg1:string):Promise<void>;

export function ListProjectWorkItems():Promise<Array<guiapp.WorkItem>>;

export function ListStopwatches():Promise<Array<guiapp.Stopwatch>>;

export function ListWorkItems():Promise<Array<guiapp.WorkItem>>;

export function SetTaskActive(arg1:number,arg2:boolean):Promise<guiapp.WorkItem>;

export function Start(arg1:number):Promise<void>;

export function Stop():Promise<guiapp.StopResult>;

export function UpdateProject(arg1:number,arg2:string):Promise<guiapp.WorkItem>;

export function UpdateTimeEntry(arg1:guiapp.CreateTimeEntryRequest):Promise<guiapp.TimeEntry>;
