// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboard() {
  return window['go']['guiapp']['App']['GetDashboard']();
}

export function Init(arg1) {
  return window['go']['guiapp']['App']['Init'](arg1);
}

export function ListWorkItems() {
  return window['go']['guiapp']['App']['ListWorkItems']();
}

export function Start(arg1) {
  return window['go']['guiapp']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['guiapp']['App']['Stop']();
}
