// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTimeEntry(arg1) {
  return window['go']['guiapp']['App']['CreateTimeEntry'](arg1);
}

export function DeleteTimeEntry(arg1) {
  return window['go']['guiapp']['App']['DeleteTimeEntry'](arg1);
}

export function DiscardRunningStopwatch() {
  return window['go']['guiapp']['App']['DiscardRunningStopwatch']();
}

export function DiscardStopwatch(arg1) {
  return window['go']['guiapp']['App']['DiscardStopwatch'](arg1);
}

export function GetDashboard() {
  return window['go']['guiapp']['App']['GetDashboard']();
}

export function GetTimeDay(arg1) {
  return window['go']['guiapp']['App']['GetTimeDay'](arg1);
}

export function Init(arg1) {
  return window['go']['guiapp']['App']['Init'](arg1);
}

export function ListStopwatches() {
  return window['go']['guiapp']['App']['ListStopwatches']();
}

export function ListWorkItems() {
  return window['go']['guiapp']['App']['ListWorkItems']();
}

export function Start(arg1) {
  return window['go']['guiapp']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['guiapp']['App']['Stop']();
}

export function UpdateTimeEntry(arg1) {
  return window['go']['guiapp']['App']['UpdateTimeEntry'](arg1);
}
