// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {guiapp} from '../models';

export function CreateDatabase(arg1:string):Promise<guiapp.DatabaseInfo>;

export function CreateProject(arg1:string):Promise<guiapp.WorkItem>;

export function CreateProjectWithTasks(arg1:string,arg2:number):Promise<guiapp.WorkItem>;

export function CreateTask(arg1:number,arg2:string):Promise<guiapp.WorkItem>;

export function CreateTimeEntry(arg1:guiapp.CreateTimeEntryRequest):Promise<guiapp.TimeEntry>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DeleteTimeEntry(arg1:number):Promise<void>;

export function DiscardRunningStopwatch():Promise<void>;

export function DiscardStopwatch(arg1:number):Promise<void>;

export function ExportTimesheetReport(arg1:guiapp.ReportRequest):Promise<string>;

export function ExportWorktimeByMonthReport(arg1:guiapp.ReportRequest):Promise<string>;

export function ExportWorktimeGroupedByProjectReport(arg1:guiapp.ReportRequest):Promise<string>;

export function ExportWorktimeProjectDetailsReport(arg1:guiapp.ReportRequest):Promise<string>;

export function ExportWorktimeTaskDetailsReport(arg1:guiapp.ReportRequest):Promise<string>;

export function GetDashboard():Promise<guiapp.Dashboard>;

export function GetDatabaseInfo():Promise<guiapp.DatabaseInfo>;

export function GetTimeDay(arg1:string):Promise<guiapp.TimeDay>;

export function GetTimesheetReport(arg1:guiapp.ReportRequest):Promise<guiapp.TimesheetReport>;

export function GetWorktimeByMonthReport(arg1:guiapp.ReportRequest):Promise<guiapp.WorktimeByMonthReport>;

export function GetWorktimeGroupedByProjectReport(arg1:guiapp.ReportRequest):Promise<guiapp.WorktimeGroupedByProjectReport>;

export function GetWorktimeProjectDetailsReport(arg1:guiapp.ReportRequest):Promise<guiapp.WorktimeProjectDetailsReport>;

export function GetWorktimeTaskDetailsReport(arg1:guiapp.ReportRequest):Promise<guiapp.WorktimeTaskDetailsReport>;

export function ImportTimeAndBill(arg1:string):Promise<guiapp.ImportResult>;

export function Init(arg1:string):Promise<void>;

export function ListProjectWorkItems():Promise<Array<guiapp.WorkItem>>;

export function ListStopwatches():Promise<Array<guiapp.Stopwatch>>;

export function ListWorkItems():Promise<Array<guiapp.WorkItem>>;

export function PreviewTimeAndBillImport(arg1:string):Promise<guiapp.ImportPreview>;

export function SelectDatabaseFile():Promise<string>;

export function SelectImportFile():Promise<string>;

export function SelectNewDatabaseFile():Promise<string>;

export function SetProjectActive(arg1:number,arg2:boolean):Promise<guiapp.WorkItem>;

export function SetTaskActive(arg1:number,arg2:boolean):Promise<guiapp.WorkItem>;

export function Start(arg1:number):Promise<void>;

export function Stop():Promise<guiapp.StopResult>;

export function SwitchDatabase(arg1:string):Promise<guiapp.DatabaseInfo>;

export function UpdateProject(arg1:number,arg2:string):Promise<guiapp.WorkItem>;

export function UpdateTask(arg1:number,arg2:string):Promise<guiapp.WorkItem>;

export function UpdateTimeEntry(arg1:guiapp.CreateTimeEntryRequest):Promise<guiapp.TimeEntry>;

export function UseDefaultDatabase():Promise<guiapp.DatabaseInfo>;
