// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDatabase(arg1) {
  return window['go']['guiapp']['App']['CreateDatabase'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['guiapp']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1, arg2) {
  return window['go']['guiapp']['App']['CreateTask'](arg1, arg2);
}

export function CreateTimeEntry(arg1) {
  return window['go']['guiapp']['App']['CreateTimeEntry'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['guiapp']['App']['DeleteProject'](arg1);
}

export function DeleteTimeEntry(arg1) {
  return window['go']['guiapp']['App']['DeleteTimeEntry'](arg1);
}

export function DiscardRunningStopwatch() {
  return window['go']['guiapp']['App']['DiscardRunningStopwatch']();
}

export function DiscardStopwatch(arg1) {
  return window['go']['guiapp']['App']['DiscardStopwatch'](arg1);
}

export function ExportTimesheetReport(arg1) {
  return window['go']['guiapp']['App']['ExportTimesheetReport'](arg1);
}

export function ExportWorktimeByMonthReport(arg1) {
  return window['go']['guiapp']['App']['ExportWorktimeByMonthReport'](arg1);
}

export function ExportWorktimeGroupedByProjectReport(arg1) {
  return window['go']['guiapp']['App']['ExportWorktimeGroupedByProjectReport'](arg1);
}

export function ExportWorktimeTaskDetailsReport(arg1) {
  return window['go']['guiapp']['App']['ExportWorktimeTaskDetailsReport'](arg1);
}

export function GetDashboard() {
  return window['go']['guiapp']['App']['GetDashboard']();
}

export function GetDatabaseInfo() {
  return window['go']['guiapp']['App']['GetDatabaseInfo']();
}

export function GetTimeDay(arg1) {
  return window['go']['guiapp']['App']['GetTimeDay'](arg1);
}

export function GetTimesheetReport(arg1) {
  return window['go']['guiapp']['App']['GetTimesheetReport'](arg1);
}

export function GetWorktimeByMonthReport(arg1) {
  return window['go']['guiapp']['App']['GetWorktimeByMonthReport'](arg1);
}

export function GetWorktimeGroupedByProjectReport(arg1) {
  return window['go']['guiapp']['App']['GetWorktimeGroupedByProjectReport'](arg1);
}

export function GetWorktimeTaskDetailsReport(arg1) {
  return window['go']['guiapp']['App']['GetWorktimeTaskDetailsReport'](arg1);
}

export function ImportTimeAndBill(arg1) {
  return window['go']['guiapp']['App']['ImportTimeAndBill'](arg1);
}

export function Init(arg1) {
  return window['go']['guiapp']['App']['Init'](arg1);
}

export function ListProjectWorkItems() {
  return window['go']['guiapp']['App']['ListProjectWorkItems']();
}

export function ListStopwatches() {
  return window['go']['guiapp']['App']['ListStopwatches']();
}

export function ListWorkItems() {
  return window['go']['guiapp']['App']['ListWorkItems']();
}

export function PreviewTimeAndBillImport(arg1) {
  return window['go']['guiapp']['App']['PreviewTimeAndBillImport'](arg1);
}

export function SelectDatabaseFile() {
  return window['go']['guiapp']['App']['SelectDatabaseFile']();
}

export function SelectImportFile() {
  return window['go']['guiapp']['App']['SelectImportFile']();
}

export function SelectNewDatabaseFile() {
  return window['go']['guiapp']['App']['SelectNewDatabaseFile']();
}

export function SetTaskActive(arg1, arg2) {
  return window['go']['guiapp']['App']['SetTaskActive'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['guiapp']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['guiapp']['App']['Stop']();
}

export function SwitchDatabase(arg1) {
  return window['go']['guiapp']['App']['SwitchDatabase'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['guiapp']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateTimeEntry(arg1) {
  return window['go']['guiapp']['App']['UpdateTimeEntry'](arg1);
}

export function UseDefaultDatabase() {
  return window['go']['guiapp']['App']['UseDefaultDatabase']();
}
